name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  #build:

  #runs-on: macOS-latest

  #steps:
  #- uses: actions/checkout@v2


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
    # - name: set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    # - name: Build with Gradle
    #   run: ./gradlew build
    #- name: "Build"
    #  uses: vgaidarji/android-github-actions/build@v1.0.0
    #- name: "Run UI Tests"
    #  uses: vgaidarji/android-github-actions-emulator@v1.0.1
  androidTest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
          FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          disable-animations: false
          script: ./gradlew connectedAndroidTest --stacktrace
      