name: Build, Test and Distribute
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: vgaidarji/android-github-actions/build@v1.0.0
      env:
        FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
        FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
      with:
        args: "./gradlew assembleDebug -PpreDexEnable=false"
     - name: Run UI Tests
      uses: vgaidarji/android-github-actions/emulator@v1.0.0
      env:
        FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
        FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
      with:
        args: "./gradlew testDebug jacocoTestReport checkstyle pmd jdepend lintDebug buildDashboard -PpreDexEnable=false"
  